openapi: 3.0.3
info:
  title: Yrkande API
  version: 1.0.0
  description: API för att hantera yrkanden.

paths:
  /yrkande:
    post:
      tags: [YrkandeController]
      operationId: postYrkande
      summary: Skapar ett nytt yrkande
      description: Skapar ett nytt yrkande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostYrkandeRequest'
            example:
              erbjudandeId: "a3b9c7b8-1234-4567-89ab-123456789abc"  
              yrkandeFrom: "2025-01-01T00:00:00Z"
              yrkandeTom: "2025-01-02T00:00:00Z"
              individYrkandeRoller:
                - individId: "58435904-c2b6-4b1f-a0ab-62f1839d8ff2"
                  yrkandeRollId: "58435904-c2b6-4b1f-a0ab-62f1839d8ff2"
              yrkatResultat:
                - from: "2025-01-01T00:00:00Z"
                  tom: "2025-01-02T00:00:00Z"
                  typ: "ERSATTNING"
                  data: "{}"
      responses:
        '201':
          description: Skapat yrkande OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostYrkandeResponse'

  /yrkande/{yrkandeId}:
    get:
      tags: [ YrkandeController ]
      operationId: getYrkande
      summary: Hämtar ett yrkande
      description: Hämtar ett yrkande baserat på dess unika ID
      parameters:
        - name: yrkandeId
          in: path
          required: true
          description: Yrkandets unika ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Yrkande hittat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Yrkande'
        '404':
          description: Yrkande hittades inte
    put: 
      tags: [YrkandeController]
      operationId: putYrkande
      summary: Uppdatera ett yrkande
      description: Uppdaterar ett befintligt yrkande
      parameters:
        - name: yrkandeId
          in: path
          required: true
          description: Yrkandets unika ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutYrkandeRequest'
      responses:
        '200':
          description: Yrkande uppdaterat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutYrkandeResponse'
        '400':
          description: Bad request
        '404':
          description: Yrkande hittades inte
          
components:
  schemas:
    Yrkande:
      type: object
      description: Yrkande
      properties:
        id:
          type: string
          description: Yrkandets unika ID
          format: uuid
        erbjudandeId:
          type: string
          description: Erbjudandets unika ID
          format: uuid
        version:
          type: integer
          description: Yrkandets version
        yrkandedatum:
          type: string
          description: Datetime när yrkandet uppstod, enligt ISO 8601
          format: date-time
        yrkandestatus:
          $ref: '#/components/schemas/Yrkandestatus'
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        avsikt:
          $ref: '#/components/schemas/Avsiktstyp'
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        yrkatResultat:
          type: array
          description: Lista av yrkade resultat
          items:
            $ref: '#/components/schemas/YrkatResultat'
      required:
        - id
        - erbjudandeId
        - version
        - yrkandedatum
        - yrkandestatus
        - yrkandeFrom
        - yrkandeTom
        - avsikt
        - individYrkandeRoller
        - yrkatResultat

    Yrkandestatus:
      type: string
      description: Yrkandestatus
      enum:
        - PLANERAT
        - YRKAT
        - UNDER_UTREDNING
        - FASTSTALLT_UNDER_UTREDNING
        - FASTSTALLT

    Avsiktstyp:
      type: string
      description: Avsiktstyp
      enum:
        - NY
        - ANDRING
        - BORTTAG
        - ATERTAGEN

    YrkatResultat:
      type: object
      description: Yrkat resultat kopplat till ett yrkande
      properties:
        id:
          type: string
          format: uuid
          description: Yrkat resultatets unika ID
        version:
          type: integer
          description: Version av yrkat resultat
        from:
          type: string
          format: date-time
          description: Startdatum/tid då resultatet gäller från, enligt ISO 8601
        tom:
          type: string
          format: date-time
          description: Slutdatum/tid då resultatet gäller till, enligt ISO 8601
        typ:
          type: string
          description: Specificerar vilket typ av resultat objekt
        data:
          type: string
          description: Json data av den typ som har angetts
      required:
        - id
        - version
        - from
        - tom
        - typ
        - data

    PostYrkandeRequest:
      type: object
      description: Data som krävs för att skapa ett nytt yrkande
      properties:
        erbjudandeId:
          type: string
          format: uuid
          description: Vilket erbjudande yrkandet avser
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        yrkatResultat:
          type: array
          description: Lista av yrkat resultat
          items:
            $ref: '#/components/schemas/YrkatResultatCreate'
      required:
        - erbjudandeId
        - yrkandeFrom
        - yrkandeTom
        - individYrkandeRoller
        - yrkatResultat
       
    PostYrkandeResponse:
      type: object
      description: Svar vid skapande av ett nytt yrkande
      properties:
        yrkande:
          $ref: '#/components/schemas/Yrkande'
      required:
        - yrkande

    PutYrkandeRequest:
      type: object
      description: Object för att uppdatera ett yrkande
      properties:
        version:
          type: integer
          description: Yrkandets version
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        yrkandestatus:
          $ref: '#/components/schemas/Yrkandestatus'
        avsikt:
          $ref: '#/components/schemas/Avsiktstyp'
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        yrkatResultat:
          type: array
          description: Lista av yrkat resultat
          items:
            $ref: '#/components/schemas/YrkatResultatCreate'
      required:
        - version
        - yrkandeFrom
        - yrkandeTom
        - yrkandestatus
        - avsikt
        - individYrkandeRoller
        - yrkatResultat

    PutYrkandeResponse:
      type: object
      description: Svar efter att ett yrkande uppdaterats
      properties:
        yrkande:
          $ref: '#/components/schemas/Yrkande'
      required:
        - yrkande

    IndividYrkandeRoll:
      type: object
      description: Representerar en individ tillsammans med dess roll
      properties:
        individId:
          type: string
          format: uuid
          description: Id till en individ
        yrkandeRollId:
          type: string
          format: uuid
          description: Id till en yrkande roll
      required:
        - individId
        - yrkandeRollId

    YrkatResultatCreate:
      type: object
      description: Data som behövs för att skapa ett yrkat resultat
      properties:
        from:
          type: string
          format: date-time
          description: Yrkat från och med datum
        tom:
          type: string
          format: date-time
          description: Yrkat till och med datum
        typ:
          type: string
          description: Specificerar vilket typ av resultat objekt
        data:
          type: string
          description: Json data av den typ som har angetts
      required:
        - from
        - tom
        - typ
        - data

    Beslutsutfall:
      type: string
      description: Beslutsutfall för ersättning
      enum:
        - JA
        - NEJ
        - FU